### ISSUE TITLE
Не стратует runserver

### ISSUE THREAD

**Issue by nucluster** [idlesign/pythonz#72]
Здравствуйте! Установку делал по инструкции из README.
Вот такой трейсбэк:

```
(venv) vladimir@ovz5:~/pythonz(master)$ pythonz
# Environment type: development
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/config.py", line 563, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/lib/python3.8/logging/config.py", line 744, in configure_handler
    result = factory(**kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1143, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.8/logging/__init__.py", line 1172, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/pythonz/debug.log'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vladimir/pythonz/venv/bin/pythonz", line 11, in <module>
    load_entry_point('pythonz', 'console_scripts', 'pythonz')()
  File "/home/vladimir/pythonz/pythonz/manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/home/vladimir/pythonz/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/vladimir/pythonz/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/vladimir/pythonz/venv/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/vladimir/pythonz/venv/lib/python3.8/site-packages/django/utils/log.py", line 75, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib/python3.8/logging/config.py", line 808, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.8/logging/config.py", line 570, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'file'
```

**Comment by idlesign** [comment]
Приветствую!

Спасибо за наводку. Актуализировал описание и добавил потерянную директорию здесь: https://github.com/idlesign/pythonz/commit/57572c274d3e16f4a895fe11ba4181b9c6312fb6

Должно помочь.

**Comment by nucluster** [comment]
Нет, не помогло. Вываливается тот же трейсбек, слово в слово (проверил диффом).
И еще, bash скрипт который runtests.sh запускает какой-то отсутствующий py.test.

**Comment by idlesign** [comment]
> Нет, не помогло. Вываливается тот же трейсбек, слово в слово (проверил диффом).

Код новый из репозитория не забыли подтянуть, директория ``state`` на месте?

> И еще, bash скрипт который runtests.sh запускает какой-то отсутствующий py.test.

Добавил файл с описанием зависимостей для тестов, дополнил ридми.

**Comment by idlesign** [comment]
Упростил задачу: добавил скрипт `boostrap.sh`.

**Comment by nucluster** [comment]
Обновил код из репозитория - заработало.
